### ISSUE TITLE
ci: smoke test is failing

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1977]
**Describe the bug**
The smoke test job started failing this morning, example here: https://github.com/penumbra-zone/penumbra/actions/runs/4136267279 

The most likely culprit is the CI-reorg PR I merged in #1971; however, the [smoke test job passed on that PR](https://github.com/penumbra-zone/penumbra/actions/runs/4129828302/jobs/7135866800), using the updated paths. It started failing on merge into main. 

I haven't been able to reproduce the smoke test failure locally yet. Working on this as high-priority, since we want open PRs to pass CI prior to merge.

**Comment by redshiftzero** [comment]
Looks like tokio-util is failing to build on 0.7.5 which was a new release today: https://github.com/tokio-rs/tokio/pull/5442

**Comment by conorsch** [comment]
Repro here: 

```
#0 26.86    Compiling pin-project v1.0.12                                                                                                                                                                                       
#0 27.07 error[E0382]: use of moved value: `id`                                                                                                                                                                                 
#0 27.07    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.7.5/src/task/join_map.rs:388:48                                                                                                         
#0 27.07     |                                                                                                                                                                                                                  
#0 27.07 365 |         let id = abort.id();                                                                                                                                                                                     
#0 27.07     |             -- move occurs because `id` has type `tokio::task::Id`, which does not implement the `Copy` trait                                                                                                   
#0 27.07 366 |         let map_key = Key { id, key };                                                                                                                                                                           
#0 27.07     |                             -- value moved here                                                                                                                                                                  
#0 27.07 ...                                                                                                                                                                                                                    
#0 27.07 388 |         let _prev = self.hashes_by_task.insert(id, hash);                                                                                                                                                        
#0 27.07     |                                                ^^ value used here after move                                                                                                                                     
#0 27.07                                                                                                                                                                                                                        
#0 27.19 For more information about this error, try `rustc --explain E0382`.                                                                                                                                                    
#0 27.20 error: could not compile `tokio-util` due to previous error                                                                                                                                                            
#0 27.20 warning: build failed, waiting for other jobs to finish...                                                                                                                                                             
------                                                                                                                                                                                                                          
failed to solve: process "/bin/sh -c cargo build --release --bin pd --target $(uname -m)-unknown-linux-gnu" did not complete successfully: exit code: 101
```

so it looks like we need some more version pinning! Huzzah. Thanks, @redshiftzero !

**Comment by conorsch** [comment]
Closed by #1978
